import { defineView, ViewKey } from "twenty-sdk/define";
import {
  BASE_FIELD_OBJECT_UNIVERSAL_IDENTIFIER,
  ALL_BASE_FIELDS_VIEW_UNIVERSAL_IDENTIFIER
} from "../constants/base-field.constants"
import {
  FIELD_1_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_2_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_3_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_4_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_5_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_6_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_7_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_8_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_9_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_10_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_11_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_12_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_13_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_14_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_15_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_16_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_17_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_18_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_19_FIELD_UNIVERSAL_IDENTIFIER,
  FIELD_20_FIELD_UNIVERSAL_IDENTIFIER
} from "../objects/base-field.object"

export default defineView({
  universalIdentifier: ALL_BASE_FIELDS_VIEW_UNIVERSAL_IDENTIFIER,
  name: "All base fields",
  objectUniversalIdentifier: BASE_FIELD_OBJECT_UNIVERSAL_IDENTIFIER,
  icon: "IconList",
  key: ViewKey.INDEX,
  position: 0,
  fields: [
    {
      universalIdentifier: "6e465ee6-02d6-4fb3-ab1f-c42c3e440ba9",
      fieldMetadataUniversalIdentifier: FIELD_1_FIELD_UNIVERSAL_IDENTIFIER,
      position: 0,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "8ddcf445-c3e8-4757-aaf9-6c75d820e2b1",
      fieldMetadataUniversalIdentifier: FIELD_2_FIELD_UNIVERSAL_IDENTIFIER,
      position: 1,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "851cbbd7-79a9-4236-b283-63d5bf07e7d4",
      fieldMetadataUniversalIdentifier: FIELD_3_FIELD_UNIVERSAL_IDENTIFIER,
      position: 2,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "27dd7fed-118e-482a-82b5-0a919cad9077",
      fieldMetadataUniversalIdentifier: FIELD_4_FIELD_UNIVERSAL_IDENTIFIER,
      position: 3,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "93366302-d287-4357-9d6f-5e72cb466036",
      fieldMetadataUniversalIdentifier: FIELD_5_FIELD_UNIVERSAL_IDENTIFIER,
      position: 4,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "d8564eb5-eca9-447d-a2ed-3cf1a0e139f7",
      fieldMetadataUniversalIdentifier: FIELD_6_FIELD_UNIVERSAL_IDENTIFIER,
      position: 5,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "2813d760-3774-49e8-bf62-7890f968d47c",
      fieldMetadataUniversalIdentifier: FIELD_7_FIELD_UNIVERSAL_IDENTIFIER,
      position: 6,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "7909543e-a9b4-4035-86fe-806a4a152929",
      fieldMetadataUniversalIdentifier: FIELD_8_FIELD_UNIVERSAL_IDENTIFIER,
      position: 7,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "1ca4b156-90bb-4c21-93cb-eeee2319183d",
      fieldMetadataUniversalIdentifier: FIELD_9_FIELD_UNIVERSAL_IDENTIFIER,
      position: 8,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "6d0e21e4-413e-46ef-a81f-cff4987aa04d",
      fieldMetadataUniversalIdentifier: FIELD_10_FIELD_UNIVERSAL_IDENTIFIER,
      position: 9,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "4c35bd23-b87f-4726-988d-33634ca2e117",
      fieldMetadataUniversalIdentifier: FIELD_11_FIELD_UNIVERSAL_IDENTIFIER,
      position: 10,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "2a28af20-6349-4f9d-b97b-70b99d5d55a6",
      fieldMetadataUniversalIdentifier: FIELD_12_FIELD_UNIVERSAL_IDENTIFIER,
      position: 11,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "31ee095b-8df2-4b6f-af06-1a568e1170ff",
      fieldMetadataUniversalIdentifier: FIELD_13_FIELD_UNIVERSAL_IDENTIFIER,
      position: 12,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "0562b396-a3fa-42cf-98da-4f62df5a5acf",
      fieldMetadataUniversalIdentifier: FIELD_14_FIELD_UNIVERSAL_IDENTIFIER,
      position: 13,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "e8efaeb9-7271-45ff-93d6-95ec7e66d439",
      fieldMetadataUniversalIdentifier: FIELD_15_FIELD_UNIVERSAL_IDENTIFIER,
      position: 14,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "682bb338-678d-4e74-bd79-5c19f376f616",
      fieldMetadataUniversalIdentifier: FIELD_16_FIELD_UNIVERSAL_IDENTIFIER,
      position: 15,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "f1c27422-42bc-4759-aa0c-4f5f125ede77",
      fieldMetadataUniversalIdentifier: FIELD_17_FIELD_UNIVERSAL_IDENTIFIER,
      position: 16,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "57dcd13a-ab10-48db-8d9e-e2ed123812e9",
      fieldMetadataUniversalIdentifier: FIELD_18_FIELD_UNIVERSAL_IDENTIFIER,
      position: 17,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "2b692b36-482f-43cc-a1e6-7dafe6e01310",
      fieldMetadataUniversalIdentifier: FIELD_19_FIELD_UNIVERSAL_IDENTIFIER,
      position: 18,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: "aa71dcee-d4b4-4cdf-8f5e-981b1a2e8771",
      fieldMetadataUniversalIdentifier: FIELD_20_FIELD_UNIVERSAL_IDENTIFIER,
      position: 19,
      isVisible: true,
      size: 200,
    }
  ],
});